#-[ PROJECT NAME
name: "cloudflare-tunnel"

#-[ SERVICES
services:
  # Cloudflare Tunnel
  cloudflared:
    image: cloudflare/cloudflared:${CLOUDFLARE_IMAGE_TAG}
    container_name: "cloudflare-tunnel"
    command: "tunnel run"
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - "cloudflare"
    restart: "unless-stopped"

#-[ NETWORKS
networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare:
    name: "cloudflare"
    driver: "bridge"
