#-[ PROJECT NAME
name: "stirling-pdf"

#-[ SERVICES
services:
  # Like Adobe Acrobat, but I don't have to sell my organs to use it
  stirling-pdf:
    image: "stirlingtools/stirling-pdf:${STIRLING_PDF_IMAGE_TAG}"
    container_name: "stirling-pdf"
    env_file: "./.env"
    networks:
      - "cloudflare"
    restart: "unless-stopped"
    volumes:
      - "stirling-pdf.data:/configs"             # Settings & database
      - "stirling-pdf.pipeline/pipeline"         # Automation configs

#-[ NETWORKS
networks:
  # Public / External Network (Cloudflare Tunnel)
  cloudflare:
    external: true

#-[ VOLUMES
volumes:
  stirling-pdf.data:
  stirling-pdf.pipeline:
